# Generated by Django 4.0.6 on 2022-07-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('creators', models.ManyToManyField(to='creators.creator')),
            ],
        ),
    ]
