# Generated by Django 4.0.6 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='sees',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
