# Generated by Django 4.0.6 on 2022-07-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmodel_image_alter_postmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='downloads',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
