# Generated by Django 4.0.6 on 2022-07-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
        ('posts', '0004_postmodel_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='creators',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='creators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creators.creator'),
        ),
    ]
