# Generated by Django 4.0.6 on 2022-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postmodel_creators_postmodel_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_top',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
