version: '3.7'

services:
  drf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf
    restart: always
    command: sh -c "gunicorn --bind 0.0.0.0:8000 muslimmind.wsgi:application"
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
      - ./media_cdn:/usr/src/app/media_cdn
      - ./static_cdn:/usr/src/app/static_cdn
    ports:
      - "8000:8000"
    depends_on:
       - db
    env_file:
       - .env

#  nginx:
#   build:
#     context: .
#     dockerfile: nginx/Dockerfile
#   volumes:
#      - ./nginx/letsencrypt/fullchain.pem:/etc/letsencrypt/live/muslimmind.uz/fullchain.pem
#      - ./nginx/letsencrypt/privkey.pem:/etc/letsencrypt/live/muslimmind.uz/privkey.pem
#      - ./media:/media
#      - ./static:/static
#      - ./media_cdn:/media_cdn
#      - ./static_cdn:/static_cdn
#   ports:
#     - "80:80" 
#     - "443:443" 

#   depends_on:
#     - drf
  db:
    image: postgres
    container_name: db
    # hostname:
    ports:
      - "5432:5432"
    restart: always
    env_file:
     - .env
    volumes:
     - pgdbdata:/var/lib/postgresql/data/






volumes:
  pgdbdata:
